insert into bookmodule_book (title, author, price, edition) values ('posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet', 'Merla Batteson', 68, 71);
insert into bookmodule_book (title, author, price, edition) values ('in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa', 'Arley Kilcullen', 85, 16);
insert into bookmodule_book (title, author, price, edition) values ('amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed', 'Consuelo Stevenson', 18, 51);
insert into bookmodule_book (title, author, price, edition) values ('lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat', 'Thia Kahane', 48, 65);
insert into bookmodule_book (title, author, price, edition) values ('urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit', 'Karoly Figgins', 62, 96);
insert into bookmodule_book (title, author, price, edition) values ('tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra', 'Betsy Peaple', 52, 37);
insert into bookmodule_book (title, author, price, edition) values ('vel enim sit amet nunc viverra dapibus nulla suscipit ligula', 'Ervin Salack', 44, 70);
insert into bookmodule_book (title, author, price, edition) values ('tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla', 'Caty Delong', 2, 99);
insert into bookmodule_book (title, author, price, edition) values ('sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet', 'Sophey Ary', 16, 45);
insert into bookmodule_book (title, author, price, edition) values ('morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien', 'Randy Lilloe', 15, 90);
insert into bookmodule_book (title, author, price, edition) values ('potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam', 'Jedediah Donoghue', 94, 4);
insert into bookmodule_book (title, author, price, edition) values ('quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla', 'Frederich Keasey', 81, 78);
insert into bookmodule_book (title, author, price, edition) values ('aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus', 'Del Sichardt', 40, 68);
insert into bookmodule_book (title, author, price, edition) values ('nisi volutpat eleifend donec ut dolor morbi vel lectus in quam', 'Odelle Ortas', 95, 25);
insert into bookmodule_book (title, author, price, edition) values ('cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus', 'Barthel Norledge', 18, 73);
insert into bookmodule_book (title, author, price, edition) values ('etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate', 'Shannan Brunsen', 98, 89);
insert into bookmodule_book (title, author, price, edition) values ('sem duis aliquam convallis nunc proin at turpis a pede', 'Olive Westell', 81, 26);
insert into bookmodule_book (title, author, price, edition) values ('donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium', 'Jean Domengue', 69, 51);
insert into bookmodule_book (title, author, price, edition) values ('augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet', 'Marcela Oxenden', 56, 33);
insert into bookmodule_book (title, author, price, edition) values ('leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa', 'Allix Torritti', 41, 6);
